from typing import TypedDict, List

class AgentState(TypedDict):
    user_request: str            # Original application prompt
    specification: str           # Markdown spec generated by PM
    source_code: str             # Python code from Software Engineer
    execution_logs: str          # Raw terminal logs (stdout/stderr) from QA tool
    qa_analysis: str             # Structural breakdown of bugs from the QA Agent
    error_count: int             # Total loop counts
    iteration_history: List[str] # Tracking log array for user visibility
